### PR TITLE
improve codebyte tag replacement on save

### PR DESCRIPTION
**Pull request by christian-dinh**
## Overview
replaces regex with new (and heavily unit-tested) `findCodeByte` function. This also means I had to add jest to this repo, as qunit just doesn't work with importing single functions (lol), but this is probably a good thing.

There is currently one case that does not quite work correctly:
```
[codebyte]
[codebyte]
[/codebyte]
```
ie, an extra opening tag. This renders sanely but breaks "save to post", not sure how much we care though 🤷 

### PR Checklist
- [ ] Related to JIRA ticket: [REACH-1006](https://codecademy.atlassian.net/browse/REACH-1006)
- [x] I have run this code to verify it works
- [x] This PR includes [client](https://www.notion.so/codecademy/Frontend-Unit-Tests-1cbf4e078a6647559b4583dfb6d3cb18), [server](https://www.notion.so/codecademy/Ruby-Unit-Tests-6f0353926a034df4909142e4fe686bf7), and/or [end to end](https://www.notion.so/codecademy/Frontend-Acceptance-Tests-cb1125a99a6c4d478a85979aa46cad03) tests for the code change

### Testing Instructions
1. run discourse locally with this branch
2. make sure "save to post" functionality works with multiple codebytes
3. run `yarn test` and make sure the tests pass

### CODE REVIEW

**Review by dougyd92 — CHANGES_REQUESTED** [review]
Nice! Tested locally and confirmed working. 

We need to move the test file into the `/test` directory, e.g. `test/javascripts/unit/code-bytes.test.js`. When I went to run the other qunit tests, it failed because it tried to load all files under `/assets` and then can't find jest.

As a followup, let's hook this up to circleci.

**Comment by christian-dinh** [comment]
@dougyd92 just a heads up, I'm not sure if there's a way to do this without adopting different naming conventions for unit and acceptance tests (`*-test.js` for acceptance, `*.test.js` for unit), are we ok with that?

**Comment by christian-dinh** [comment]
added a minimal circle config that _should_ hopefully work for us. It occurred to me recently that this repo has no lint enforcement so we'll probably want to add that to the CI workflow eventually

**Review by dougyd92 — APPROVED** [review]
Nice!
Yeah the file name differences are a little clunky but it's good that it's documented here.

**Comment by christian-dinh** [comment]
update; the config worked!
https://app.circleci.com/pipelines/github/Codecademy/discourse-codebytes-plugin/1/workflows/50f8de25-d79e-4cd1-aaea-37fe9bb67ef0/jobs/2

**Pull request merged**
